# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Asoode' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Asoode
  pod 'GoogleSignIn', '~> 5.0.0'

  target 'Asoode-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AsoodeTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
